resources:
- ../base
namespace: sample
patchesStrategicMerge:
- replica-count.yaml
- resource.yaml
images:
- name: sample-image
  newName: nginx
  newTag: 1.19.6
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
