apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nginx
spec:
  template:
    spec:
      containers:
        - name: sample-nginx
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 500m
